### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by sindresorhus** [tunnckoCore/hasha-cli#2]
I really don't see the point of this. Hasha has a CLI and you're depending on Hasha, meaning this package is actually larger. And you also expose the API, which makes this package just a duplicate of Hasha. I was planning to extract the Hasha CLI into a separate module, so can I please have this npm name so I can do it the right way? `$ npm owner add sindresorhus hasha-cli` Thanks :)

**Comment by tunnckoCore** [comment]
It's strange that you are asking. But yea, you're right. I intentionally just duplicate the CLI part of Hasha, so you can just remove it, then we can remove `index.js` and just use `hasha` in `cli.js` :+1: 

PRs welcome, i'll merge and add you ASAP.

**Comment by sindresorhus** [comment]
No, it's strange that you just copy-paste the code and readme from my module and call it your own.

I'm not asking to be able to contribute to this. I'm asking for the npm name. I have my own plan for the Hasha CLI and you're interfering with it.

**Comment by tunnckoCore** [comment]
Okey. But sorry, where i showing/saying that it's my? https://github.com/tunnckoCore/hasha-cli/blob/master/cli.js#L2-L7 - index.js oneline require is written by me, lol.

Nevermind.

**Comment by tunnckoCore** [comment]
ooh, the license.md file, okey sorry. just forgot to change it, due to use automation a lot.

**Comment by sindresorhus** [comment]
So, can you please give me the npm name?

```
$ npm owner add sindresorhus hasha-cli
```

**Comment by tunnckoCore** [comment]
```
[charlike@dev]$ npm owner add sindresorhus hasha-cli
+ sindresorhus (hasha-cli)
```

done. im curios what different you'll do.
